sudo: required
services: 
 - docker

before_install:
 - docker build -t masuqur/docker-react -f Dockerfile.dev .

script:
 - docker run masuqur/docker-react npm run test -- --coverage

deploy:
 provider: elasticbeanstalk
 region: "us-east-1"
 app: "docker-react"
 env: "Docker-react-env"
 # bucket-name: "elasticbeanstalk-us-east-1-670026337301"
 bucket-name:  "elasticbeanstalk-us-east-1-557690577839"
 bucket-path: "docker-react"
 on:
  branch: main
 access_key_id: $AWS_ACCESS_KEY_MUHAMMAD
 secret_access_key: $AWS_SECRET_KEY_MUHAMMAD
 skip_cleanup: true
 debug: true
