sudo: required
services: 
 - docker

before_install:
 - docker build -t masuqur/docker-react -f Dockerfile.dev .

script:
 - docker run masuqur/docker-react npm run test -- --coverage

deploy:
 provider: elasticbeanstalk
 region: "us-east-1"
 app: "docker-run"
 env: "Docker-run-env"
 bucket-name: "elasticbeanstalk-us-east-1-670026337301"
 bucket-path: "docker-run"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key:
  secure: "$AWS_SECRET_KEY"
